variables:
  ARTIFACT_PATH: dist/
  PY_VERSION: '3.9'                          # Set Python version if you must
  PYTHONIOENCODING: 'utf-8'

  
build:
  script:
    - python -m pip install pyinstaller
    - python -m pip install pybuilder
    - pyb -X


include: 'http://aibspi.corp.alleninstitute.org/infrastructure/mpeci/raw/master/resources/gitlab-ci-template.yml'
