variables:
  ARTIFACT_PATH: dist/
  PY_VERSION: '3.9.5'                          # Set Python version if you must
  PYTHONIOENCODING: 'utf-8'


build:
  script:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - python.exe  setup.py -v clean --all sdist
    - python.exe  setup.py -v clean --all bdist_wheel


build_docs:
  extends: build
  stage: build
  # before_script: 
  script: 
    - python -m pip install -r requirements_dev.txt
    - sphinx-build -M html docs/source/ public_html


include: 'http://aibspi.corp.alleninstitute.org/infrastructure/mpeci/raw/master/resources/gitlab-ci-template.yml'
