variables:
  ARTIFACT_PATH: dist/

  # Set Python version if you must
  PY_VERSION: '3.6'

  # Set additional conda specs if you want:
  CONDA_SPECS: pip=10.0.1 setuptools=39.0.1

build:
  script:
# Build with pybuilder
    - python -m pip install pyinstaller==3.6
    - python -m pip install pybuilder==0.11.17
    - pyb_ -CX




# Everything else that will be run is defined here:
include: 'http://aibspi.corp.alleninstitute.org/infrastructure/mpeci/raw/master/resources/gitlab-ci-template.yml'
